config/routes.rb
Rails.application.routes.draw do
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html

  root to: "alerts#index"

  resources :alerts do
    member do
      post :unverify
      post :verify
      post :reject
      post :resolve
    end
  end

  resources :runs, only: [:index]

  namespace :api do
    namespace :v1 do
      resources :agents, only: [:index, :create, :show]
      resources :alerts, only: [:index, :create, :show] do
        collection do
          post :obsolete
        end
      end
      resources :runs, only: [:index, :create, :update, :show]
    end
  end
end

app/models/alert.rb
class Alert < ApplicationRecord

  include AASM
  include Discard::Model

  belongs_to :kind
  belongs_to :family
  belongs_to :source
  belongs_to :agent
  belongs_to :run

  belongs_to :severity_internal, class_name: 'Severity'
  belongs_to :severity_external, class_name: 'Severity'

  has_many :alert_departments, dependent: :destroy
  has_many :alert_users, dependent: :destroy

  has_many :departments, through: :alert_departments
  has_many :users, through: :alert_users

  has_many :audits, dependent: :destroy
  has_many :urls, dependent: :destroy
  has_many :key_values, dependent: :destroy

  validates :state, presence: true
  validates :kind, presence: true
  validates :family, presence: true
  validates :source, presence: true
  validates :name, presence: true
  validates :finding, presence: true
  validates :finding_id, presence: true
  validates :first_detected_at, presence: true

  after_create :touch_source_last_seen
  after_create :log_create_event

  aasm column: 'state' do
    after_all_transitions :log_status_change

    state :unverified, initial: true
    state :verified
    state :rejected
    state :resolved
    state :obsoleted

    event :unverify do
      transitions from: [:verified], to: :unverified
    end

    event :verify, after: :set_verified_at do
      transitions from: [:unverified], to: :verified
    end

    event :reject, after: :set_rejected_at do
      transitions from: [:verified, :unverified], to: :rejected
    end

    event :resolve, after: :set_resolved_at do
      transitions from: [:unverified, :verified], to: :resolved
    end

    event :obsolete, after: :set_obsoleted_at do
      transitions from: [:verified, :unverified], to: :obsoleted
    end
  end

  scope :state, ->(state) { where('state IN (?)', state) }
  scope :kind, ->(kind) { joins(:kind).where('kinds.slug IN (?)', kind) }
  scope :family, ->(family) { joins(:family).where('families.slug IN (?)', family) }
  scope :severity, ->(severity) { joins(:severity_internal).where('severities.slug IN (?)', severity) }
  scope :source, ->(source) { joins(:source).where('sources.slug IN (?)', source) }
  scope :department, ->(department) { joins(:departments).where('departments.slug IN (?)', department) }
  scope :user, ->(user) { joins(:users).where('users.slug IN (?)', user) }

  private

  def set_rejected_at
    update_attribute(:rejected_at, Time.now.utc)
  end

  def set_resolved_at
    update_attribute(:resolved_at, Time.now.utc)
  end

  def set_obsoleted_at
    update_attribute(:obsoleted_at, Time.now.utc)
  end

  def set_verified_at
    update_attribute(:verified_at, Time.now.utc)
  end

  def log_create_event
    audits.create(created_at: first_detected_at, kind: 'detected', action: 'Created Alert', icon: 'fas fa-exclamation-circle')
  end

  def log_status_change
    icon = 'fas fa-check-circle' if aasm.to_state == 'resolved'
    icon = 'fas fa-minus-circle' if aasm.to_state == 'obsoleted'
    audits.create(kind: 'status change', action: "Set to #{aasm.to_state}", icon: icon)
  end

  def touch_source_last_seen
    source.touch(:last_seen_at)
    source.touch(:last_alert_at)
  end

end

app/controllers/alerts_controller.rb
class AlertsController < ApplicationController

  before_action :find_alert, only: %i[show edit update unverify verify reject resolve]

  def index
    @alerts = Alert.kept.includes(:severity_internal)

    if params[:alert]
      @filter_params = params.require(:alert).permit(
        states: [],
        severities: [],
        kinds: [],
        families: [],
        sources: [],
        departments: [],
        users: []
      )

      @alerts = @alerts.state(@filter_params[:states])           if @filter_params[:states]
      @alerts = @alerts.severity(@filter_params[:severities])    if @filter_params[:severities]
      @alerts = @alerts.kind(@filter_params[:kinds])             if @filter_params[:kinds]
      @alerts = @alerts.family(@filter_params[:families])        if @filter_params[:families]
      @alerts = @alerts.source(@filter_params[:sources])         if @filter_params[:sources]
      @alerts = @alerts.department(@filter_params[:departments]) if @filter_params[:departments]
      @alerts = @alerts.user(@filter_params[:users])             if @filter_params[:users]
    else
      @filter_params = {}
      @filter_params[:states] = %w[unverified verified]
      @alerts = @alerts.state(@filter_params[:states])
    end

    @pagy, @alerts = pagy(@alerts.order('severities.order desc, last_detected_at desc'))
  end

  def show
    respond_to do |format|
      format.html
      format.js { render layout: false }
    end
  end

  def edit
    respond_to do |format|
      format.js { render layout: false }
    end
  end

  def update
    if @alert.update_attributes(alert_params)
      respond_to do |format|
        format.html { redirect_to alert_url }
        format.json { render json: @alert, status: :created, serializer: Api::V1::AlertSerializer }
      end
    else
      respond_to do |format|
        format.html { render :edit }
        format.json { render json: @alert.errors, status: :unprocessable_entity }
      end
    end
  end

  def unverify
    @alert.unverify!
    respond_to do |format|
      format.html { redirect_to alert_url }
      format.json { render json: @alert, status: :created, serializer: Api::V1::AlertSerializer }
    end
  end

  def verify
    @alert.verify!
    respond_to do |format|
      format.html { redirect_to alert_url }
      format.json { render json: @alert, status: :created, serializer: Api::V1::AlertSerializer }
    end
  end

  def reject
    @alert.reject!
    respond_to do |format|
      format.html { redirect_to alert_url }
      format.json { render json: @alert, status: :created, serializer: Api::V1::AlertSerializer }
    end
  end

  def resolve
    @alert.resolve!
    respond_to do |format|
      format.html { redirect_to alert_url }
      format.json { render json: @alert, status: :created, serializer: Api::V1::AlertSerializer }
    end
  end

  private

  def find_alert
    @alert = Alert.kept.find(params[:id])
  end

  def alert_params
    params.require(:alert).permit(
      :notes,
      :kind_id,
      :family_id,
      :severity_internal_id,
      :ticket,
      department_ids: [],
      user_ids: []
    )
  end

end

app/controllers/api/v1/alerts_controller.rb
class Api::V1::AlertsController < Api::V1::BaseController

  def index
    alerts = Alert.kept
    render json: alerts, each_serializer: Api::V1::AlertSerializer
  end

  def show
    alert = Alert.kept.find(params[:id])
    render json: alert, serializer: Api::V1::AlertSerializer
  end

  def create
    alert = Alert.find_or_initialize_by(
      source: Source.find_or_initialize_by(slug: alert_params[:source]),
      finding_id: alert_params[:finding_id],
      target: alert_params[:target]
    )

    alert_params[:urls].map do |url|
      alert.urls.find_or_initialize_by(name: url[:name], url: url[:url])
    end if alert_params[:urls]

    alert_params[:key_values].map do |kv|
      alert.key_values.find_or_initialize_by(key: kv[:key], value: kv[:value])
    end if alert_params[:key_values]

    alert.last_detected_at = alert_params[:last_detected_at]
    alert.finding = alert_params[:finding]
    alert.severity_external = Severity.friendly.find(alert_params[:severity])
    alert.agent_id = alert_params[:agent_id]
    alert.run_id = alert_params[:run_id]

    if alert.persisted?
      alert.detail = alert_params[:detail]
      unless alert_params[:no_repeat]
        alert.count = alert_params[:count].nil? ? alert.count + 1 : alert_params[:count]
        alert.audits.build(created_at: alert_params[:detected_at], kind: 'detected', action: 'Repeat Alert', icon: 'fas fa-exclamation-circle')
      end
    else
      alert.count = alert_params[:count].nil? ? 1 : alert_params[:count]
      alert.name = alert_params[:name]
      alert.detail = alert_params[:detail]
      alert.first_detected_at = alert_params[:first_detected_at]
      alert.notes = alert_params[:notes]
      alert.kind = Kind.friendly.find(alert_params[:kind])
      alert.family = Family.friendly.find(alert_params[:family])
      alert.severity_internal = Severity.friendly.find(alert_params[:severity])
      alert.departments << alert_params[:departments].map { |d| Department.friendly.find(d) } if alert_params[:departments]
    end

    alert.save!
    render json: alert, serializer: Api::V1::AlertSerializer
  end

  def obsolete
    source = Source.kept.find_by(slug: alert_params[:source])
    alerts = source.alerts.kept.verified.or(Alert.unverified). \
      where(agent_id: alert_params[:agent_id]). \
      where.not(run_id: alert_params[:run_id]). \
      each(&:obsolete!)

    render json: alerts, each_serializer: Api::V1::AlertSerializer
  end

  private

  def alert_params
    params.permit(
      :name,
      :target,
      :detail,
      :notes,
      :finding,
      :finding_id,
      :first_detected_at,
      :last_detected_at,
      :kind,
      :family,
      :source,
      :severity,
      :no_repeat,
      :count,
      :agent_id,
      :run_id,
      urls: [:name, :url],
      key_values: [:key, :value],
      departments: []
    )
  end

end

app/views/alerts/_alert.html.haml
.title
  = alert.name
  %span.id= alert.id
%div
  .rightbar
    .header{:style => "margin-top: 0px"} Details
    %table.table.table-striped.table-hover.table-sm
      %tbody
        %tr
          %td.key Department
          %td.detail= editable(alert, :departments, :name)
        %tr
          %td.key Assigned
          %td.detail= editable(alert, :users, :name)
        %tr
          %td.key Ticket
          %td.detail= editable(alert, :ticket)

    .header Detections
    %table.table.table-striped.table-hover.table-sm
      %tbody
        %tr
          %td.key Count
          %td.detail= alert.count
        %tr
          %td.key First
          %td.detail= alert.first_detected_at
        - if alert.first_detected_at != alert.last_detected_at
          %tr
            %td.key Last
            %td.detail= alert.last_detected_at

    .header Dates
    %table.table.table-striped.table-hover.table-sm
      %tbody
        - if alert.assigned_at
          %tr
            %td.key Assigned
            %td.detail= alert.assigned_at
        - if alert.verified_at
          %tr
            %td.key Verified
            %td.detail= alert.verified_at
        - if alert.rejected_at
          %tr
            %td.key Rejected
            %td.detail= alert.rejected_at
        - if alert.resolved_at
          %tr
            %td.key Resolved
            %td.detail= alert.resolved_at
        - if alert.obsoleted_at
          %tr
            %td.key Obsoleted
            %td.detail= alert.obsoleted_at
        %tr
          %td.key Created
          %td.detail= alert.created_at
        %tr
          %td.key Updated
          %td.detail= alert.updated_at

    - if alert.assigned_at or not alert.unverified?
      .header Time Frames
      %table.table.table-striped.table-hover.table-sm
        %tbody
          - if alert.assigned_at
            %tr
              %td.key Detected → Assigned
              %td.detail= distance_of_time_in_words(alert.first_detected_at, alert.assigned_at)
          - if alert.verified_at
            %tr
              %td.key Detected → Verified
              %td.detail= distance_of_time_in_words(alert.first_detected_at, alert.verified_at)
          - if alert.rejected_at
            %tr
              %td.key Detected → Rejected
              %td.detail= distance_of_time_in_words(alert.first_detected_at, alert.rejected_at)
          - if alert.resolved_at
            %tr
              %td.key Detected → Resolved
              %td.detail= distance_of_time_in_words(alert.first_detected_at, alert.resolved_at)
            - if alert.verified_at
              %tr
                %td.key Verified → Resolved
                %td.detail= distance_of_time_in_words(alert.verified_at, alert.resolved_at)

    - if alert.key_values.any?
      .header Key Value
      %table.table.table-striped.table-hover.table-sm
        %tbody
          - alert.key_values.each do |kv|
            %tr
              %td.key= kv.key
              %td.detail= kv.value

    .header{:style => "margin-top: 0px"} Last Agent
    %table.table.table-striped.table-hover.table-sm
      %tbody
        - if alert.agent
          %tr
            %td.key UUID
            %td.detail-sm= alert.agent_id
          %tr
            %td.key Name
            %td.detail= alert.agent.check

    .header{:style => "margin-top: 0px"} Last Run
    %table.table.table-striped.table-hover.table-sm
      %tbody
        - if alert.run
          %tr
            %td.key UUID
            %td.detail-sm= alert.run_id
          %tr
            %td.key Started At
            %td.detail= alert.run.started_at
          %tr
            %td.key Ended At
            %td.detail= alert.run.ended_at

  .row.basic
    .col
      .key Type
      = editable(alert, :kind, :name)
    .col
      .key Family
      = editable(alert, :family, :name)
    .col
      .key Source
      %i{class: alert.source.icon}
      = alert.source.name
  .row.basic
    .col
      .key External Severity
      %span.badge{style: "background: #{alert.severity_external.color}"}= alert.severity_external.name
    .col
      .key Internal Severity
      = editable(alert, :severity_internal, :name, style: "background: #{alert.severity_internal.color}")
  .row.basic
    .col
      .key Finding ID
      %pre
        %code= alert.finding_id
    - if alert.target
      .col
        .key Target
        %pre
          %code= alert.target
    - if alert.detail
      .col
        .key Detail
        %pre
          %code= alert.detail

  %hr/

  .row.basic
    .col
      - if alert.unverified?
        %a.badge{class: "state state-unverified-bg flash"}
          %i.fa-fw.fas.fa-question-circle
          Unverified
      - elsif alert.may_unverify?
        = link_to unverify_alert_path(alert), remote: true, data: { type: :json }, method: :post, class: 'badge state state-unverified-bg' do
          %i.fa-fw.fas.fa-question-circle
          Unverified
      - else
        %span.badge{class: "state state-unverified-bg"}
          %i.fa-fw.fas.fa-question-circle
          Unverified

    .col-1
      %i.fas.fa-exchange-alt

    .col
      - if alert.verified?
        %a.badge{class: "state state-verified-bg flash"}
          %i.fa-fw.fas.fa-plus-circle
          Verified
      - elsif alert.may_verify?
        = link_to verify_alert_path(alert), remote: true, data: { type: :json }, method: :post, class: 'badge state state-verified-bg' do
          %i.fa-fw.fas.fa-plus-circle
          Verified
      - else
        %span.badge{class: "state state-verified-bg"}
          %i.fa-fw.fas.fa-plus-circle
          Verified

    .col-1
      %i.fas.fa-long-arrow-alt-right

    .col
      - if alert.rejected?
        %a.badge{class: "state state-rejected-bg flash"}
          %i.fa-fw.fas.fa-times-circle
          Rejected
      - elsif alert.may_reject?
        = link_to reject_alert_path(alert), remote: true, data: { type: :json }, method: :post, class: 'badge state state-rejected-bg' do
          %i.fa-fw.fas.fa-times-circle
          Rejected
      - else
        %span.badge{class: "state state-rejected-bg"}
          %i.fa-fw.fas.fa-times-circle
          Rejected

      - if alert.resolved?
        %a.badge{class: "state state-resolved-bg flash"}
          %i.fa-fw.fas.fa-check-circle
          Resolved
      - elsif alert.may_resolve?
        = link_to resolve_alert_path(alert), remote: true, data: { type: :json }, method: :post, class: 'badge state state-resolved-bg' do
          %i.fa-fw.fas.fa-check-circle
          Resolved
      - else
        %span.badge{class: "state state-resolved-bg"}
          %i.fa-fw.fas.fa-check-circle
          Resolved

      - if alert.obsoleted?
        %a.badge{class: "state state-obsoleted-bg flash"}
          %i.fa-fw.fas.fa-minus-circle
          Obsoleted

  - if alert.urls.any?
    %hr/
    %h5 URLs
    %ul
      - alert.urls.each do |url|
        %li
          = url.name
          %small (#{link_to url.url, url.url, target: '_blank'})

  - if alert.notes?
    %hr/
    %h5 Notes
    %p= alert.notes

  %hr/
  %h5 Raw Finding
  %pre
    %code.raw= JSON.pretty_generate(JSON.parse(alert.finding))

  %hr/
  %h5 Timeline
  - alert.audits.order('created_at desc').each do |audit|
    .row.timeline
      .col-1.pip
        %i{class: audit.icon || 'fas fa-dot-circle'}
      .col.date= audit.created_at
      .col.action= audit.kind
      .col.detail= audit.action
      -# .col.author= audit.author

app/views/alerts/edit.js.haml
= form_for(@alert, remote: true, data: { type: :json }, html: { class: 'form-inline editable' }) do |f|

  - if params[:field] == 'ticket'
    .form-group.mr-2
      = f.text_field :ticket, class: 'form-control form-control-sm'

  - elsif params[:field] == 'kind'
    .form-group.mr-2
      = f.collection_select :kind_id, Kind.kept.all, :id, :name, {}, class: 'form-control form-control-sm'

  - elsif params[:field] == 'family'
    .form-group.mr-2
      = f.collection_select :family_id, Family.kept.all, :id, :name, {}, class: 'form-control form-control-sm'

  - elsif params[:field] == 'departments'
    .form-group.mr-2
      = f.collection_select :department_ids, Department.kept.all, :id, :name, { include_blank: '' }, :multiple => true, class: 'form-control form-control-sm'

  - elsif params[:field] == 'users'
    .form-group.mr-2
      = f.collection_select :user_ids, User.kept.all, :id, :name, { include_blank: '' }, :multiple => true, class: 'form-control form-control-sm'

  - elsif params[:field] == 'severity_internal'
    .form-group.mr-2
      = f.collection_select :severity_internal_id, Severity.kept.all, :id, :name, {}, class: 'form-control form-control-sm'

  = f.button class: 'btn btn-sm btn-warning', data: { disable_with: "<i class='fas fa-spinner fa-spin'></i>" } do
    %i.fas.fa-edit

app/views/alerts/index.haml
.row
  .alerts.col-3.col-sm-5.col-md-4.col-lg-3.col-xl-3{style: ''}
    .filter-box
      %button.filter.btn.btn-sm.btn-secondary{"aria-controls" => "collapse", "aria-expanded" => "false", "data-target" => "#collapse", "data-toggle" => "collapse", :type => "button"}
        %i.fa-fw.fas.fa-filter
      .title Filters
      #collapse.collapse
        = form_tag alerts_path, method: :get do
          .form-group.row
            %label.col-sm-2.col-form-label{:for => "alert_states"} State
            .col
              = filter(:alert, :states, Alert.aasm.states, :name, :name, @filter_params.nil? ? [] : @filter_params[:states])

          .form-group.row
            %label.col-sm-2.col-form-label{:for => "alert_severities_"} Severity
            .col
              = filter(:alert, :severities, Severity.kept.all.order(order: :desc), :slug, :name, @filter_params.nil? ? [] : @filter_params[:severities])

          .form-group.row
            %label.col-sm-2.col-form-label{:for => "alert_kinds_"} Kind
            .col
              = filter(:alert, :kinds, Kind.kept.all.order(:name), :slug, :name, @filter_params.nil? ? [] : @filter_params[:kinds])

          .form-group.row
            %label.col-sm-2.col-form-label{:for => "alert_families_"} Family
            .col
              = filter(:alert, :families, Family.kept.all.order(:name), :slug, :name, @filter_params.nil? ? [] : @filter_params[:families])

          .form-group.row
            %label.col-sm-2.col-form-label{:for => "alert_sources_"} Source
            .col
              = filter(:alert, :sources, Source.kept.all.order(:name), :slug, :name, @filter_params.nil? ? [] : @filter_params[:sources])

          .form-group.row
            %label.col-sm-2.col-form-label{:for => "alert_departments_"} Dept
            .col
              = filter(:alert, :departments, Department.kept.all.order(:name), :slug, :name, @filter_params.nil? ? [] : @filter_params[:departments])

          .form-group.row
            %label.col-sm-2.col-form-label{:for => "alert_users_"} User
            .col
              = filter(:alert, :users, User.kept.all.order(:name), :slug, :name, @filter_params.nil? ? [] : @filter_params[:users])

          .form-group.row
            .col
              = button_tag 'Apply Filters', class: 'btn btn-sm btn-primary filter-submit'

    - @alerts.each do |alert|
      = link_to alert_path(alert), class: 'alert-box', style: "background-color: #{alert.severity_internal.color}", remote: true do
        .icons
          %i.fa-fw{title: alert.kind.name, class: alert.kind.icon}
          %i.fa-fw{title: alert.family.name, class: alert.family.icon}
        .source-icon
          %i.fa-fw.fa-5x{class: alert.source.icon}
        .title
          - if alert.unverified?
            %span.fa-layers.fa-fw
              %i.fas.fa-circle.state-unverified
              %i.fas.fa-question-circle{title: 'Unverified', "data-fa-transform" => "shrink-6"}
          - if alert.verified?
            %span.fa-layers.fa-fw
              %i.fas.fa-circle.state-verified
              %i.fas.fa-plus-circle{title: 'Verified', "data-fa-transform" => "shrink-6"}
          - if alert.rejected?
            %span.fa-layers.fa-fw
              %i.fas.fa-circle.state-rejected
              %i.fas.fa-times-circle{title: 'Rejected', "data-fa-transform" => "shrink-6"}
          - if alert.resolved?
            %span.fa-layers.fa-fw
              %i.fas.fa-circle.state-resolved
              %i.fas.fa-check-circle{title: 'Resolved', "data-fa-transform" => "shrink-6"}
          - if alert.obsoleted?
            %span.fa-layers.fa-fw
              %i.fas.fa-circle.state-obsoleted
              %i.fas.fa-minus-circle{title: 'Obsoleted', "data-fa-transform" => "shrink-6"}
          #{alert.name}
          - if alert.count > 1
            %small x#{alert.count}
        .target= alert.target
        .detail= alert.detail
        .source= alert.source.name
        .date= alert.last_detected_at

    = pagy_bootstrap_nav(@pagy).html_safe
  .alert-detail.col-9.offset-3.offset-sm-5.offset-md-4.offset-lg-3.offset-xl-3

app/views/alerts/show.html.haml
.row
  .alert-detail.col
    = render partial: 'alert', locals: { alert: @alert }

app/views/alerts/show.js.erb
$(".alert-detail").html("<%= escape_javascript(render partial: 'alert', locals: { alert: @alert } ) %>"); 