config/routes.rb
Rails.application.routes.draw do
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html

  root to: "alerts#index"

  resources :alerts do
    member do
      post :unverify
      post :verify
      post :reject
      post :resolve
    end
  end

  resources :runs, only: [:index]

  namespace :api do
    namespace :v1 do
      resources :agents, only: [:index, :create, :show]
      resources :alerts, only: [:index, :create, :show] do
        collection do
          post :obsolete
        end
      end
      resources :runs, only: [:index, :create, :update, :show]
    end
  end
end

app/views/layouts/_navigation.haml
.col-sidebar.col-fixed-primary.text-center
  .top
    %nav.nav
      %a.nav-link.logo{href: "/"}
        %i.fas.fa-chess-rook.fa-fw{alt: "Garrison Logo", style: "font-size:2.5em;", title: "Garrison"}

      .divider Type
      - Kind.kept.all.each do |kind|
        = link_to alerts_path(alert: { kinds: [kind.slug], states: ['unverified', 'verified'] }), title: kind.name, class: 'nav-link' do
          %span.fa-layers.fa-fw{style: "font-size: 2.5em"}
            %i.fa-fw{class: kind.icon}
            - if kind.alerts.state(:unverified).count > 0
              %span.fa-layers-counter.state-unverified-bg{title: 'Unverified'}= kind.alerts.state(:unverified).count
            - if kind.alerts.state(:verified).count > 0
              %span.fa-layers-counter.state-verified-bg{title: 'Verified', style: 'top: 16px'}= kind.alerts.state(:verified).count

      .divider Family
      - Family.kept.all.each do |family|
        = link_to alerts_path(alert: { families: [family.slug], states: ['unverified', 'verified'] }), title: family.name, class: 'nav-link' do
          %span.fa-layers.fa-fw{style: "font-size: 2.5em"}
            %i.fa-fw{class: family.icon}
            - if family.alerts.state(:unverified).count > 0
              %span.fa-layers-counter.state-unverified-bg{title: 'Unverified'}= family.alerts.state(:unverified).count
            - if family.alerts.state(:verified).count > 0
              %span.fa-layers-counter.state-verified-bg{title: 'Verified', style: 'top: 16px'}= family.alerts.state(:verified).count

      .divider Utility
      = link_to runs_path, title: "Runs", class: 'nav-link' do
        %span.fa-layers.fa-fw{style: "font-size: 2.5em"}
          %i.fa-fw.fas.fa-running
  -# .bottom
  -#   %nav.nav
  -#     .dropup
  -#       %a.nav-link{"data-toggle" => "dropdown", href: "", title: "Profile"}
  -#         %i.fas.fa-user-shield{style: "font-size: 2.5em"}
  -#       .dropdown-menu
  -#         %h6.dropdown-header Lloyd
  -#         .dropdown-divider
  -#         %a.dropdown-item{href: "/profile"}
  -#           %i.far.fa-fw.fa-user
  -#           Your Profile
  -#         %a.dropdown-item{href: "/users/edit"}
  -#           %i.fas.fa-shield-alt
  -#           Security Settings
  -#         .dropdown-divider
  -#         %a.dropdown-item{"data-method" => "delete", href: "/sign_out", rel: "nofollow"}
  -#           %i.fas.fa-sign-out-alt
  -#           Sign Out

app/views/layouts/application.haml
!!!
%html{lang: "en"}
  %head
    %meta{content: "text/html; charset=UTF-8", "http-equiv" => "Content-Type"}/
    %meta{charset: "utf-8"}/
    %meta{content: "width=device-width, initial-scale=1, shrink-to-fit=no", name: "viewport"}/
    %title Garrison
    = csrf_meta_tags
    = csp_meta_tag
    = stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload'
    = javascript_include_tag 'application', 'data-turbolinks-track': 'reload'
    = render 'application/favicon'
  %body
    .container-fluid
      .row
        = render partial: 'layouts/navigation'
        .content.col.col-offset-sidebar
          = yield
          %footer
            = link_to 'https://github.com/forward3d/garrison', target: '_blank' do
              %i.fab.fa-fw.fa-github
              Garrison